input {
    http {
        port => 5044
    }
}

filter {
    mutate {
        add_field => { "service" => "MyApp" }
    }
}

output {
    elasticsearch {
        hosts => ["http://elasticsearch:9200"]
        index => "logs-myapp-%{+YYYY.MM.dd}"
    }
}
