// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WarehouseWorker.Application.Infrastructure.Persistence;

#nullable disable

namespace Warehouse.Application.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Shared.Domain.JobExecutionHistory<WarehouseWorker.Application.Domain.PackageTrackingEvent>", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ExecutedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("JobExecutionHistories");
                });

            modelBuilder.Entity("WarehouseWorker.Application.Domain.Package", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Packages");
                });

            modelBuilder.Entity("WarehouseWorker.Application.Domain.PackageTrackingEvent", b =>
                {
                    b.Property<string>("PackageId")
                        .HasColumnType("text");

                    b.Property<string>("ExecutionId")
                        .HasColumnType("text");

                    b.Property<string>("CurrentStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PackageId", "ExecutionId");

                    b.HasIndex("ExecutionId");

                    b.ToTable("PackageTrackingEvents");
                });

            modelBuilder.Entity("WarehouseWorker.Application.Domain.PackageTrackingEvent", b =>
                {
                    b.HasOne("Shared.Domain.JobExecutionHistory<WarehouseWorker.Application.Domain.PackageTrackingEvent>", "ExecutionHistory")
                        .WithMany("_trackingEvents")
                        .HasForeignKey("ExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WarehouseWorker.Application.Domain.Package", "Package")
                        .WithMany("_trackingEvents")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExecutionHistory");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("Shared.Domain.JobExecutionHistory<WarehouseWorker.Application.Domain.PackageTrackingEvent>", b =>
                {
                    b.Navigation("_trackingEvents");
                });

            modelBuilder.Entity("WarehouseWorker.Application.Domain.Package", b =>
                {
                    b.Navigation("_trackingEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
