// <auto-generated />
using ShippingWorker.Application.Infrastructure.Persistence;

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Shipping.Application.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ShippingWorker.Application.Domain.JobExecutionHistory", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ExecutedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("JobExecutionHistories");
                });

            modelBuilder.Entity("ShippingWorker.Application.Domain.Shipment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Shipments");
                });

            modelBuilder.Entity("ShippingWorker.Application.Domain.ShipmentTrackingEvent", b =>
                {
                    b.Property<string>("ShipmentId")
                        .HasColumnType("text");

                    b.Property<string>("ExecutionId")
                        .HasColumnType("text");

                    b.Property<string>("CurrentStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ShipmentId", "ExecutionId");

                    b.HasIndex("ExecutionId");

                    b.ToTable("ShipmentTrackingEvents");
                });

            modelBuilder.Entity("ShippingWorker.Application.Domain.ShipmentTrackingEvent", b =>
                {
                    b.HasOne("ShippingWorker.Application.Domain.JobExecutionHistory", "ExecutionHistory")
                        .WithMany("_trackingEvents")
                        .HasForeignKey("ExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShippingWorker.Application.Domain.Shipment", "Shipment")
                        .WithMany("_trackingEvents")
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExecutionHistory");

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("ShippingWorker.Application.Domain.JobExecutionHistory", b =>
                {
                    b.Navigation("_trackingEvents");
                });

            modelBuilder.Entity("ShippingWorker.Application.Domain.Shipment", b =>
                {
                    b.Navigation("_trackingEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
